/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as flpCrowndsaleSol from "./FLPCrowndsale.sol";
export type { flpCrowndsaleSol };
import type * as tokenSol from "./Token.sol";
export type { tokenSol };
export type { GamePlay } from "./GamePlay";
